### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Scrumplex** [intel/helm-charts#10]
I would like to contribute, but I don't feel comfortable contributing when this repo doesn't have a license.

**Comment by poussa** [comment]
@Scrumplex thanks for the issue. We'll add the license shortly.

**Comment by poussa** [comment]
@Scrumplex now all but one charts has the license in place. Does this address you concerns?

**Comment by Scrumplex** [comment]
Yes that looks excellent. Thanks!
