### ISSUE TITLE
make nodeSelector unconfigured in values?

### ISSUE THREAD

**Issue by budimanjojo** [intel/helm-charts#27]
Hi, the current `values.yaml` file in `gpu-device-plugin` is pre filled with `intel.feature.node.kubernetes.io/gpu: 'true'` and there's no way to override that because it's a mapping and it will just add the user defined one to the map. maybe make the logic to default to `intel.feature.node.kubernetes.io/gpu: 'true'` if the value is not defined instead?

**Comment by mythi** [comment]
@budimanjojo all of our `*-device-plugin` charts have the same limitation. Currently our thinking is we keep it like this and make NFD as the mandatory dependency (see #26). Do you have case where you'd prefer sunning the plugin without any `nodeSelector` values so that the plugin runs on *all* nodes?

**Comment by budimanjojo** [comment]
@mythi okay fair enough. I'm running NFD too but I didn't apply the NFD config patch so I wanted to just do `nodeSelector: feature.node.kubernetes.io/pci-0300_8086.present: "true"` because I only have one type of gpu. But I just applied the NFD config patch and now I'm good. I'll close this issue now.

**Comment by 2fst4u** [comment]
> @mythi okay fair enough. I'm running NFD too but I didn't apply the NFD config patch so I wanted to just do `nodeSelector: feature.node.kubernetes.io/pci-0300_8086.present: "true"` because I only have one type of gpu. But I just applied the NFD config patch and now I'm good. I'll close this issue now.

What patch did you need to apply? I can't find any reference to how to make this label automatically apply to nodes.

**Comment by mythi** [comment]
@2fst4u install GPU plugin helm chart using `--set nodeFeatureRule=true`
