### ISSUE TITLE
Include nfd rules in chart?

### ISSUE THREAD

**Issue by javydekoning** [intel/helm-charts#31]
I noticed the NFD rules are not part of this helm chart, hence those need to be manually deployed. 

Shouldn't these be part of the chart? Or at-least made optional through `values.yaml`? 

Today, I have to separately deploy the rules like so: 
 
```sh
kubectl apply -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v0.26.0'
```

**Comment by mythi** [comment]
> Or at-least made optional through `values.yaml`?

they are available but not enabled by default:

```
helm install <PLUGIN> intel/intel-device-plugins-<PLUGIN> --namespace inteldeviceplugins-system --create-namespace \
  --set nodeFeatureRule=true
```

**Comment by javydekoning** [comment]
Thanks, I was looking at the wrong chart. 

Found it here:

https://github.com/intel/helm-charts/blob/main/charts/gpu-device-plugin/values.yaml#L20
